all: release debug

#/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids/Makefile._MLWeightedCentroids.Release: /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids/_MLWeightedCentroids.pro
#	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids && /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/ThirdParty/Python/Release/bin/python /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/BuildSystem/BuildTools/Scripts/createProject.py _MLWeightedCentroids
#/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids/Makefile._MLWeightedCentroids.Debug: /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids/_MLWeightedCentroids.pro
#	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids && /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/ThirdParty/Python/Release/bin/python /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/BuildSystem/BuildTools/Scripts/createProject.py _MLWeightedCentroids

release: #/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids/Makefile._MLWeightedCentroids.Release
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids
	$(MAKE) -k -j 4 -f Makefile._MLWeightedCentroids.Release
debug: #/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids/Makefile._MLWeightedCentroids.Debug 
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids 
	$(MAKE) -k -j 4 -f Makefile._MLWeightedCentroids.Debug
cleanall: clean
cleanrelease:
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids && if test -e Makefile._MLWeightedCentroids.Release; then $(MAKE) -k -f Makefile._MLWeightedCentroids.Release clean; fi
cleandebug:
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLWeightedCentroids && if test -e Makefile._MLWeightedCentroids.Debug; then $(MAKE) -k -f Makefile._MLWeightedCentroids.Debug clean; fi

clean: cleanrelease cleandebug

rebuilddebug: cleandebug debug

rebuildrelease: cleanrelease release
