//----------------------------------------------------------------------------------
//! _MLFilterLabelByVolume module definitions.
/*!
// \file    FilterLabelByVolume.script
// \author     wieke
// \date    2014-05-08
*/
//----------------------------------------------------------------------------------


Window {
  Vertical {
    margin = 3
    Field threshold {
      tooltip = "Threshold (in voxels)"
    }
  }
}