all: release debug

#/home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask/Makefile._MLFrontBackMask.Release: /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask/_MLFrontBackMask.pro
#	cd /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask && /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/ThirdParty/Python/Release/bin/python /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/BuildSystem/BuildTools/Scripts/createProject.py _MLFrontBackMask
#/home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask/Makefile._MLFrontBackMask.Debug: /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask/_MLFrontBackMask.pro
#	cd /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask && /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/ThirdParty/Python/Release/bin/python /opt/MeVisLab2.5.1GCC-4.6.3/Packages/MeVis/BuildSystem/BuildTools/Scripts/createProject.py _MLFrontBackMask

release: #/home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask/Makefile._MLFrontBackMask.Release
	cd /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask
	$(MAKE) -k -j 4 -f Makefile._MLFrontBackMask.Release
debug: #/home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask/Makefile._MLFrontBackMask.Debug 
	cd /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask 
	$(MAKE) -k -j 4 -f Makefile._MLFrontBackMask.Debug
cleanall: clean
cleanrelease:
	cd /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask && if test -e Makefile._MLFrontBackMask.Release; then $(MAKE) -k -f Makefile._MLFrontBackMask.Release clean; fi
cleandebug:
	cd /home/wieke/git-workplace/cadmi/ANODE09/General/Sources/ML/_MLFrontBackMask && if test -e Makefile._MLFrontBackMask.Debug; then $(MAKE) -k -f Makefile._MLFrontBackMask.Debug clean; fi

clean: cleanrelease cleandebug

rebuilddebug: cleandebug debug

rebuildrelease: cleanrelease release
