all: release debug

#/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax/Makefile._MLLabelledMax.Release: /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax/_MLLabelledMax.pro
#	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax && /opt/MeVisLab/Packages/MeVis/ThirdParty/Python/Release/bin/python /opt/MeVisLab/Packages/MeVis/BuildSystem/BuildTools/Scripts/createProject.py _MLLabelledMax
#/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax/Makefile._MLLabelledMax.Debug: /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax/_MLLabelledMax.pro
#	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax && /opt/MeVisLab/Packages/MeVis/ThirdParty/Python/Release/bin/python /opt/MeVisLab/Packages/MeVis/BuildSystem/BuildTools/Scripts/createProject.py _MLLabelledMax

release: #/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax/Makefile._MLLabelledMax.Release
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax
	$(MAKE) -k -j 4 -f Makefile._MLLabelledMax.Release
debug: #/home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax/Makefile._MLLabelledMax.Debug 
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax 
	$(MAKE) -k -j 4 -f Makefile._MLLabelledMax.Debug
cleanall: clean
cleanrelease:
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax && if test -e Makefile._MLLabelledMax.Release; then $(MAKE) -k -f Makefile._MLLabelledMax.Release clean; fi
cleandebug:
	cd /home/wieke/git-workspace/cadmi/ANODE09/General/Sources/ML/_MLLabelledMax && if test -e Makefile._MLLabelledMax.Debug; then $(MAKE) -k -f Makefile._MLLabelledMax.Debug clean; fi

clean: cleanrelease cleandebug

rebuilddebug: cleandebug debug

rebuildrelease: cleanrelease release
