//----------------------------------------------------------------------------------
//! DIAGMultiRegionGrowing module definitions.
/*!
// \file    MultiRegionGrowing.script
// \author  Wieke
// \date    2014-06-27
*/
//----------------------------------------------------------------------------------


Window {
  Vertical {
    margin = 3
    Field tolerance {
      tooltip = "Tolerance"
    }
  }
}