//----------------------------------------------------------------------------------
//! DIAGMultiRegionGrowing module definitions.
/*!
// \file    MultiRegionGrowing.script
// \author     wieke
// \date    2014-07-01
*/
//----------------------------------------------------------------------------------


Window {
  Vertical {
    margin = 3
    Field tolerance {
      tooltip = "Tolerance"
    }
    Field size {
      tooltip = "Size"
    }
  }
}